<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>a4b67df2-5596-4e97-8728-0af08c0007eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>header > a > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/header/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>554788d9-adb4-4d90-98cf-15b25b5aa08f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/Toolsqa.jpg</value>
      <webElementGuid>dfdec7a6-497c-4cbb-8af7-eb59885b4565</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/header[1]/a[1]/img[1]</value>
      <webElementGuid>81f1a403-38d0-49fc-903d-b5be4b527bf9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/header/a/img</value>
      <webElementGuid>63da93be-1ad8-4498-8e04-4eeca907114c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/a/img</value>
      <webElementGuid>9962f14a-5654-46b0-b719-5f01bbb275ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/images/Toolsqa.jpg']</value>
      <webElementGuid>0d545884-94e1-407e-8f80-e048347c1212</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
