<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Company_company</name>
   <tag></tag>
   <elementGuidId>58d5b295-decc-4b05-a760-478d62c29e06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;company&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='company']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Enter your company&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>96068cdc-c1ed-46db-a52c-e32337653b3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>company</value>
      <webElementGuid>181f569c-e916-4550-af84-14d51ee88ef4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7e4d697d-bbc6-4d08-a6cd-15a5089bd871</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f7f38566-48b6-4609-8c70-1de9a79e6c01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your company</value>
      <webElementGuid>eca4de92-4996-4603-9e72-b4fdb54922c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;page-content&quot;]/div[@class=&quot;elementor elementor-1097&quot;]/section[@class=&quot;elementor-section elementor-top-section elementor-element elementor-element-0731668 elementor-section-boxed elementor-section-height-default elementor-section-height-default&quot;]/div[@class=&quot;elementor-container elementor-column-gap-default&quot;]/div[@class=&quot;elementor-column elementor-col-50 elementor-top-column elementor-element elementor-element-b7d792b&quot;]/div[@class=&quot;elementor-widget-wrap elementor-element-populated&quot;]/div[@class=&quot;elementor-element elementor-element-459c920 elementor-widget__width-inherit elementor-widget elementor-widget-html&quot;]/div[@class=&quot;elementor-widget-container&quot;]/div[@class=&quot;userform&quot;]/div[@class=&quot;content block panel check-height  parent-inline-cont&quot;]/div[@class=&quot;element-companyId&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;input-group input-block&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>1dc92e08-6260-45f9-bf99-72fc44e9b842</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='company']</value>
      <webElementGuid>527063b2-efdf-40e3-aad3-7da9190f2814</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='content']/div/div/section[2]/div/div/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>b888c5f7-4b42-4efb-b6d7-c7bd662d8467</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/input</value>
      <webElementGuid>6981353d-d829-4667-8d27-46c3775be208</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'company' and @type = 'text' and @placeholder = 'Enter your company']</value>
      <webElementGuid>4c460457-72dc-4bf8-a0a7-eb5ae469e058</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
